name: Deploy to IPFS
on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: popovoleksandr/ipfs-pinata-deploy-action@v1.0.1
        with:
          pin-name: 'My Website'
          path: '.'
          pinata-api-key: ${{ secrets.PINATA_API_KEY }}
          pinata-secret-api-key: ${{ secrets.PINATA_SECRET_KEY }}
