name: Deploy to IPFS
on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deploy to IPFS
        uses: web3-storage/add-to-web3@v2.1.0
        with:
          web3_token: ${{ secrets.PINATA_API_KEY }}
          path_to_add: '.'
